name: build
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  job:
    name: Build project
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-static

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'x64'
          buildPreset: 'x64-release'

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: live_driving_64
          path: build/x64/Release